### ISSUE TITLE
TypeError: h5py objects cannot be pickled

### ISSUE THREAD

**Issue by sjq-shanghai** [ranjaykrishna/SST#8]
Traceback (most recent call last):
  File "D:/paper_with_code/SST-master/train.py", line 283, in <module>
    train(epoch, w1)
  File "D:/paper_with_code/SST-master/train.py", line 240, in train
    for batch_idx, (features, masks, labels) in enumerate(train_loader):
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
    w.start()
  File "D:\Anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "D:\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "D:\Anaconda3\lib\site-packages\h5py\_hl\base.py", line 308, in __getnewargs__
    raise TypeError("h5py objects cannot be pickled")
TypeError: h5py objects cannot be pickled

ranjaykrishna Do you know what's the problem here, thx.

**Comment by mugenggeng** [comment]
Sorry to bother you, could you please provide a copy of your data set hd5y file, because the official download is no longer available, thank you very much, my email is :mugenggeng@163.com

**Comment by mugenggeng** [comment]
> Traceback (most recent call last): File "D:/paper_with_code/SST-master/train.py", line 283, in train(epoch, w1) File "D:/paper_with_code/SST-master/train.py", line 240, in train for batch_idx, (features, masks, labels) in enumerate(train_loader): File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 278, in **iter** return _MultiProcessingDataLoaderIter(self) File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 682, in **init** w.start() File "D:\Anaconda3\lib\multiprocessing\process.py", line 112, in start self._popen = self._Popen(self) File "D:\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen return _default_context.get_context().Process._Popen(process_obj) File "D:\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen return Popen(process_obj) File "D:\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in **init** reduction.dump(process_obj, to_child) File "D:\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump ForkingPickler(file, protocol).dump(obj) File "D:\Anaconda3\lib\site-packages\h5py_hl\base.py", line 308, in **getnewargs** raise TypeError("h5py objects cannot be pickled") TypeError: h5py objects cannot be pickled
> 
> ranjaykrishna Do you know what's the problem here, thx.

Sorry to bother you, could you please provide a copy of your data set hd5y file, because the official download is no longer available, thank you very much, my email is :mugenggeng@163.com
